name: Release

on:
  push:
    tags:
      - 'v*'

defaults:
  run:
    shell: bash -l {0}

jobs:
  release:
    if: github.repository == 'Nixtla/mlforecast'
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Install build dependencies
        run: python -m pip install build wheel

      - name: Build distributions
        run: python -m build -sw

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.pypi_token }}
